In [ ]:
import numpy as np
import pandas as pd
from sklearn import tree

from sklearn import tree
#import pydotplus
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import matplotlib.image as pltimg


In [ ]:
df=pd.read_csv("./kaggle/input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

# Checking Datatypes

In [ ]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

# Converting string into float/int

In [ ]:
d0 = {'Female': 0, 'Male': 1}
df['gender'] = df['gender'].map(d0)
d = {'No': 0, 'Yes': 1}
df['Partner'] = df['Partner'].map(d)
df['Dependents'] = df['Dependents'].map(d)
df['PhoneService'] = df['PhoneService'].map(d)
d1={'No': 0, 'Yes': 1,'No phone service':2}
df['MultipleLines'] = df['MultipleLines'].map(d1)
df['OnlineSecurity'] = df['OnlineSecurity'].map(d)

In [ ]:
df.dtypes

customerID           object
gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService      object
OnlineSecurity      float64
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

# Splitting the data

In [ ]:
X=df.iloc[:10,1:4] #features
Y=df.iloc[:10,-1] #target/class

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.7, random_state=123) #test size as 30% and random state as 123, random state is for our output can be replicated


# Training the algorithm

In [ ]:
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y_train_encoded = le.fit_transform(Y_train)

xg_cl=xgb.XGBClassifier(objective='binary:logistic', seed=123) #XGBoost classifier syntax 
xg_cl.fit(X_train, Y_train_encoded) #fix model on X_train and Y_train 


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

# Train Accuracy

In [ ]:
xg_cl.score(X_train,Y_train_encoded) #train accuracy on traning set


0.6666666666666666

# Test Accuracy

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y_test_encoded = le.fit_transform(Y_test)

xg_cl.score(X_test, Y_test_encoded) #test accuracy on traning set

0.5714285714285714

# Prediction

In [ ]:
Yp=xg_cl.predict(X_test)
Yp

array([0, 0, 0, 0, 0, 0, 0])

In [ ]:
Y

0     No
1     No
2    Yes
3     No
4    Yes
5    Yes
6     No
7     No
8    Yes
9     No
Name: Churn, dtype: object

# Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test_encoded,Yp)
cm

array([[4, 0],
       [3, 0]], dtype=int64)

# Prediction 

In [ ]:
Y_pred=xg_cl.predict(X_test)
Y_pred

array([0, 0, 0, 0, 0, 0, 0])

# Prediction Accuracy

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test_encoded,Y_pred)

0.5714285714285714